---
- name: Azure Monitor exporter program binary transfer.
  unarchive:
    src: 'azure-metrics-exporter.tar.xz'
    dest: '/usr/local/bin'
    owner: 'prometheus'
    group: 'prometheus'
    mode: '0755'
  notify: 'Ensure Azure Monitor exporter service is enabled.'

- name: Azure Monitor service file transfer.
  template:
    src: 'azure_metrics_exporter.service.j2'
    dest: '/lib/systemd/system/azure_metrics_exporter.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Ensure Azure Monitor exporter service is enabled.'
