---
- name: Prober exporters YAML file transfer
  copy:
    src: '{{ item }}.yml'
    dest: '/etc/prometheus/{{ item }}.yml'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ prometheus_prober_exporters }}'
  register: prober_yaml

- name: Prober exporters configure file transfer
  template:
    src: '{{ item }}_exporter.j2'
    dest: '/etc/default/{{ item }}_exporter'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ prometheus_prober_exporters }}'
  register: prober_config

- name: Prober exporters systemd file transfer
  template:
    src: '{{ item }}_exporter.service.j2'
    dest: '/lib/systemd/system/{{ item }}_exporter.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ prometheus_prober_exporters }}'
  register: prober_system
