---
- name: Prober exporters configure file transfer
  template:
    src: '{{ item }}_exporter.j2'
    dest: '/etc/default/{{ item }}'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ prometheus_prober_exporters }}'
  register: prober_config

- name: Prober exporters systemd file transfer
  template:
    src: '{{ item }}_exporter.service.j2'
    dest: '/lib/systemd/system/{{ item }}.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ prometheus_prober_exporters }}'
  register: prober_system

- name: Register exporter service with an http health check
  uri:
    url: 'http://{{ item }}:{{ consul_public_http_port }}/v1/agent/service/register'
    method: 'PUT'
    body: '{"tags":["prometheus","exporter"],"ID":"{{ inventory_hostname | upper }}_blackbox_exporter","name":"blackbox_exporter","address":"{{ ansible_default_ipv4.address }}","port":{{ prometheus_port.blackbox }},"meta":{"instance":"{{ inventory_hostname | upper }}","group":"{{ group_names[0] | upper }}","environment":"{{ environments | upper }}"},"checks":[{"http":"http://{{ ansible_default_ipv4.address }}:{{ prometheus_port.blackbox }}/metrics","interval":"60s","tls_skip_verify":true,"method":"HEAD","timeout":"10s"}]}'
    body_format: 'json'
    status_code: '200'
    headers:
      X-Consul-Token: '{{ consul_public_exporter_token }}'
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
  environment:
    no_proxy: '{{ item }}'
  loop: '{{ consul_public_clients|flatten(levels=1) }}'
  when: consul_public_register | bool
  register: register_status
  until: register_status.status == 200
  retries: 3
  delay: 3
  no_log: true
  changed_when: false
  failed_when: false

- name: Register exporter service with an http health check
  uri:
    url: 'http://{{ item }}:{{ consul_public_http_port }}/v1/agent/service/register'
    method: 'PUT'
    body: '{"tags":["prometheus","exporter"],"ID":"{{ inventory_hostname | upper }}_snmp_exporter","name":"snmp_exporter","address":"{{ ansible_default_ipv4.address }}","port":{{ prometheus_port.snmp }},"meta":{"instance":"{{ inventory_hostname | upper }}","group":"{{ group_names[0] | upper }}","environment":"{{ environments | upper }}"},"checks":[{"http":"http://{{ ansible_default_ipv4.address }}:{{ prometheus_port.snmp }}/metrics","interval":"60s","tls_skip_verify":true,"method":"HEAD","timeout":"10s"}]}'
    body_format: 'json'
    status_code: '200'
    headers:
      X-Consul-Token: '{{ consul_public_exporter_token }}'
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
  environment:
    no_proxy: '{{ item }}'
  loop: '{{ consul_public_clients|flatten(levels=1) }}'
  when: consul_public_register | bool
  register: register_status
  until: register_status.status == 200
  retries: 3
  delay: 3
  no_log: true
  changed_when: false
  failed_when: false
