---
- name: Prober exporters configure file transfer
  template:
    src: '{{ item }}.j2'
    dest: '/etc/default/{{ item }}'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ prometheus_prober_exporters }}'
  register: prober_config

- name: Prober exporters systemd file transfer
  template:
    src: '{{ item }}.service.j2'
    dest: '/lib/systemd/system/{{ item }}.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ prometheus_prober_exporters }}'
  register: prober_system
