---
- name: Prober exporters YAML file transfer.
  copy:
    src: '{{ item }}.yml'
    dest: '/etc/prometheus/{{ item }}.yml'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ prometheus_prober_exporters }}'
  notify: 'Restart prober exporter service.'

- name: Prober exporters configure file transfer.
  template:
    src: '{{ item }}.j2'
    dest: '/etc/default/{{ item }}'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ prometheus_prober_exporters }}'
  notify: 'Restart prober exporter service.'

- name: Prober exporters systemd file transfer.
  template:
    src: '{{ item }}.service.j2'
    dest: '/lib/systemd/system/{{ item }}.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ prometheus_prober_exporters }}'
  notify: 'Restart prober exporter service.'