---
- name: Gathering service facts.
  service_facts:
  register: services_state

- name: Firewalld operation.
  block:
    - name: Allow Prometheus service port.
      firewalld:
        port: '{{ item.value }}/tcp'
        permanent: 'true'
        immediate: 'true'
        state: 'enabled'
      loop: '{{ prometheus_port | dict2items }}'
    - name: Allow Thanos service port.
      firewalld:
        port: '{{ item.value }}/tcp'
        permanent: 'true'
        immediate: 'true'
        state: 'enabled'
      loop: '{{ thanos_port | dict2items }}'
      when: thanos_is_install | bool
  when:
    - services_state.ansible_facts.services["firewalld.service"] is defined
    - services_state.ansible_facts.services["firewalld.service"].state == 'running'
