---
- name: Gathering service facts
  service_facts:
  register: services_state

- name: Allow prometheus service port
  firewalld:
    port: '{{ item.value }}/tcp'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  loop:
    - '{{ prometheus_port | dict2items }}'
    - '{{ thanos_port | dict2items }}'
    - '{{ trickster_port | dict2items }}'
  when:
    - services_state.ansible_facts.services["firewalld.service"] is defined
    - services_state.ansible_facts.services["firewalld.service"].state == 'running'
