---
- name: Include tasks for specific OS.
  include: '{{ ansible_os_family }}.yml'

- name: Configure the prometheus firewall.
  include: 'firewall.yml'

- name: Include prometheus tasks.
  include: 'prometheus.yml'

- name: Include prober exporter tasks.
  include: 'exporter.yml'

- name: Include thanos tasks.
  include: 'thanos.yml'
  when: thanos_is_install | bool

- name: Force the handler to run immediately.
  meta: flush_handlers

- name: Ensure MTA service is enabled.
  systemd:
    name: 'postfix.service'
    enabled: 'yes'
    state: 'started'

- name: Registered with HashiCorp Consul.
  include: 'register.yml'
  when:
    - exporter_is_install | bool
    - consul_public_register | bool