---
- name: Include OS-specific variables.
  include_vars: '{{ ansible_os_family }}.yml'

- name: Add prometheus YUM repositories.
  yum_repository:
    name: '{{ prometheus_repo_name }}'
    description: '{{ prometheus_repo_name }} YUM repository'
    file: '{{ prometheus_repo_name }}'
    baseurl: '{{ prometheus_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the prometheus.
  yum:
    name: '{{ item.package }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: prom_soft_updated
  until: prom_soft_updated is succeeded
  loop: '{{ prometheus_software }}'
  when: item.create | default(true) | bool
  retries: 5
  delay: 2
  notify: 'Restart prometheus service.'

- name: Install the prober exporters.
  yum:
    name: '{{ prometheus_prober_exporters }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: prom_prober_soft_updated
  until: prom_prober_soft_updated is succeeded
  retries: 5
  delay: 2
  notify: 'Restart prober exporter service.'