---
- name: Add prometheus YUM repositories
  yum_repository:
    name: '{{ prometheus_repo_name }}'
    description: '{{ prometheus_repo_name }} YUM repository'
    file: '{{ prometheus_repo_name }}'
    baseurl: '{{ prometheus_repo_url }}'
    gpgcheck: no

- name: Install the prometheus
  yum:
    name: '{{ ",".join(vars["prometheus_software"]) }}'
    state: present
  register: soft_updated
