---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Add prometheus YUM repositories
  yum_repository:
    name: '{{ prometheus_repo_name }}'
    description: '{{ prometheus_repo_name }} YUM repository'
    file: '{{ prometheus_repo_name }}'
    baseurl: '{{ prometheus_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the prometheus
  yum:
    name: '{{ ",".join(vars["prometheus_software"]) }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: soft_updated

- name: Install the prober exporters
  yum:
    name: '{{ "_exporter,".join(vars["prometheus_prober_exporters"]) }}_exporter'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  when: prometheus_prober_exporters is defined
  register: prober_soft_updated
