---
- name: Thanos base components systemd service file transfer.
  template:
    src: 'thanos-{{ item }}.service.j2'
    dest: '/lib/systemd/system/thanos-{{ item }}.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ thanos_base_components }}'
  notify: 'Restart thanos base components service.'

- name: Thanos base components default file transfer.
  template:
    src: 'thanos-{{ item }}.default.j2'
    dest: '/etc/default/thanos-{{ item }}'
    backup: 'yes'
    owner: 'prometheus'
    group: 'prometheus'
    mode: '0640'
  loop: '{{ thanos_base_components }}'
  notify: 'Restart thanos base components service.'

- name: Creating Thanos data folder.
  file:
    dest: '{{ prometheus_data_path }}/thanos'
    state: 'directory'
    owner: 'prometheus'
    group: 'prometheus'
    mode: '0750'
  when: thanos_bucket_is_used | bool

- name: Thanos cache config file transfer.
  template:
    src: 'cache.yml.j2'
    dest: '{{ prometheus_data_path }}/thanos/cache.yml'
    backup: 'no'
    owner: 'prometheus'
    group: 'prometheus'
    mode: '0640'

- name: Thanos objstore config file transfer.
  template:
    src: 'bucket.yml.j2'
    dest: '{{ prometheus_data_path }}/thanos/bucket.yml'
    backup: 'yes'
    owner: 'prometheus'
    group: 'prometheus'
    mode: '0640'
  when: thanos_bucket_is_used | bool
  notify: 'Restart thanos base components service.'

- name: Thanos optional components systemd service file transfer.
  template:
    src: 'thanos-{{ item }}.service.j2'
    dest: '/lib/systemd/system/thanos-{{ item }}.service'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ thanos_opti_components }}'
  when: thanos_bucket_is_used | bool
  notify: 'Restart thanos optional components service.'

- name: Thanos optional components default file transfer.
  template:
    src: 'thanos-{{ item }}.default.j2'
    dest: '/etc/default/thanos-{{ item }}'
    backup: 'yes'
    owner: 'prometheus'
    group: 'prometheus'
    mode: '0640'
  loop: '{{ thanos_opti_components }}'
  when: thanos_bucket_is_used | bool
  notify: 'Restart thanos optional components service.'

- name: Creating Thanos compact process folder.
  file:
    dest: '{{ prometheus_data_path }}/compact'
    state: 'directory'
    owner: 'prometheus'
    group: 'prometheus'
    mode: '0750'
  when:
    - thanos_bucket_is_used | bool
    - prometheus_server[0] in ansible_default_ipv4.address

- name: Thanos stand alone components systemd service file transfer.
  template:
    src: 'thanos-{{ item }}.service.j2'
    dest: '/lib/systemd/system/thanos-{{ item }}.service'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ thanos_stand_components }}'
  when:
    - thanos_bucket_is_used | bool
    - prometheus_server[0] in ansible_default_ipv4.address
  notify: 'Restart thanos stand alone components service.'

- name: Thanos stand alone components default file transfer.
  template:
    src: 'thanos-{{ item }}.default.j2'
    dest: '/etc/default/thanos-{{ item }}'
    backup: 'yes'
    owner: 'prometheus'
    group: 'prometheus'
    mode: '0640'
  loop: '{{ thanos_stand_components }}'
  when:
    - thanos_bucket_is_used | bool
    - prometheus_server[0] in ansible_default_ipv4.address
  notify: 'Restart thanos stand alone components service.'
