---
- name: Check current trickster version
  command: '/usr/local/bin/trickster --version'
  register: trickster_current_version
  changed_when: false
  failed_when: false

- name: Delete existing trickster version if different
  file:
    path: '/usr/local/bin/trickster'
    state: 'absent'
  when:
    - trickster_current_version.stdout is defined
    - trickster_arg.version not in trickster_current_version.stdout

- name: Install trickster
  block:
    - name: Trickster download
      unarchive:
        src: '{{ trickster_soft_url }}/v{{ trickster_arg.version }}/trickster-{{ trickster_arg.version }}.{{ ansible_system|lower }}-{{ architecture[ansible_architecture] }}.tar.gz'
        dest: '/usr/local/bin'
        owner: 'prometheus'
        group: 'prometheus'
        mode: '0755'
        remote_src: 'yes'
        validate_certs: 'no'
      register: trickster_update
      until: trickster_update is succeeded
      retries: 3
      delay: 5
    - name: Trickster program rename
      shell: 'mv /usr/local/bin/OPATH/trickster-{{ trickster_arg.version }}.{{ ansible_system|lower }}-{{ architecture[ansible_architecture] }} /usr/local/bin/trickster'
      when: trickster_update is succeeded
    - name: Trickster uncompress folder destroy
      file:
        path: '/usr/local/bin/OPATH'
        state: 'absent'
      when: trickster_update is succeeded
    - name: Trickster permission
      file:
        path: '/usr/local/bin/trickster'
        owner: 'prometheus'
        group: 'prometheus'
        mode: '0755'
      when: trickster_update is succeeded
      register: trickster_upgrade
  when:
    - trickster_current_version.rc == 2 or trickster_arg.version not in trickster_current_version.stdout
  ignore_errors: true

- name: Trickster systemd service file transfer
  template:
    src: 'trickster.service.j2'
    dest: '/lib/systemd/system/trickster.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: trickster_systemd

- name: Trickster configure file transfer
  template:
    src: 'trickster.conf.j2'
    dest: '/etc/trickster.conf'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: trickster_config
