---
- name: Restart prometheus service
  systemd:
    name: '{{ item }}'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  loop: '{{ prometheus_service }}'

- name: Restart prober exporter service
  systemd:
    name: '{{ item }}.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  loop: '{{ prometheus_prober_exporters }}'

- name: Reload prometheus service
  systemd:
    name: '{{ item }}'
    state: 'reloaded'
  loop: '{{ prometheus_service }}'

- name: Restart consul-template service
  systemd:
    name: 'consul-template'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'

- name: Restart thanos base components service
  systemd:
    name: 'thanos-{{ item }}.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  loop: '{{ thanos_base_components }}'

- name: Restart thanos optional components service
  systemd:
    name: 'thanos-{{ item }}.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  loop: '{{ thanos_opti_components }}'

- name: Restart thanos stand alone components service
  systemd:
    name: 'thanos-{{ item }}.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  loop: '{{ thanos_stand_components }}'

- name: Restart trickster service
  systemd:
    name: 'trickster.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
